<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>详解Java中的异常体系结构（throw，throws，try-catch，finally，自定义异常） - 编程学习者</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:url" content="https://bcxuexizhe.github.io/posts/136e2fdf90b6f8c7a989daa789699750/">
  <meta property="og:site_name" content="编程学习者">
  <meta property="og:title" content="详解Java中的异常体系结构（throw，throws，try-catch，finally，自定义异常）">
  <meta property="og:description" content="目录
一.异常的概念
二.异常的体系结构
三.异常的处理
异常处理思路
LBYL：Look Before You Leap
EAFP: It&#39;s Easier to Ask Forgiveness than Permission
异常抛出throw
异常的捕获
提醒声明throws
try-catch捕获处理
finally的作用
四.自定义异常类
一.异常的概念 有一句话说的很好 ”程序员不是在写BUG就是在改BUG” ，在日常开发中，程序员绞尽脑汁的去写出完美的代码，但是在程序运行过程中难免回遇见一些奇奇怪怪的问题。而这些问题与BUG总是很难去控制，用人类的思维去看明明是很完美的一个逻辑处理，但是交给编译器就产生的结果总会与我们的预期大相径庭，在Java中，我们将程序执行过程中发生的不正常的行为称为异常，比如什么算数异常啊，数组越界异常啊，空指针异常啊这都属于异常的范围，我们统称为异常
System.out.println(10 / 0); // 执行结果Exception in thread &#34;main&#34; java.lang.ArithmeticException int[] arr1 = {1, 2, 3}; System.out.println(arr1[100]); // 执行结果Exception in thread &#34;main&#34; java.lang.ArrayIndexOutOfBoundsException int[] arr2 = null; System.out.println(arr2.length); // 执行结果Exception in thread &#34;main&#34; java.lang.NullPointerException 并且我们可以看见在Java中对于不同的异常，都有对应的类来描述
二.异常的体系结构 实际上异常的种类是很多的，为了应对不同的异常或者错误，Java提供了一个非常庞大的异常体系机构供程序员来更好的维护代码的安全性，如下图所示
异常可能发生在编译阶段，可能发生在运行阶段，因此我们可以按照异常发生的时间段将其进行分类：
编译时异常，也叫做受查异常运行时异常，也叫做非受查异常 但是诸如将单词拼写错误导致的问题我们程序出现问题的情况不属于异常
三.异常的处理 代码中存在异常并不是什么奇怪的事情，但是在出现异常后，我们需要及时通知程序员去修改，对于异常的处理，我们分为俩种思路
异常处理思路 LBYL：Look Before You Leap 也就是说我们在操作之前就对异常做出充分的检查，也就是事先防御型，比如我们在设计一款游戏的时候，我们就需要对其中可能发生的每一个错误做出处理机制和避免机制">
  <meta property="og:locale" content="zh_CN">
  <meta property="og:type" content="article">
    <meta property="article:section" content="posts">
    <meta property="article:published_time" content="2023-12-06T09:58:29+08:00">
    <meta property="article:modified_time" content="2023-12-06T09:58:29+08:00">

	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
  


</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="编程学习者" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">编程学习者</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">详解Java中的异常体系结构（throw，throws，try-catch，finally，自定义异常）</h1>
			
		</header>
		<div id="gatop"></div>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <p class="img-center"><img alt="" height="320" src="https://images2.imgbox.com/38/a8/nNKR4ycV_o.gif" width="601"></p> 
<hr> 
<p id="main-toc"><strong>目录</strong></p> 
<p id="%E4%B8%80.%E5%BC%82%E5%B8%B8%E7%9A%84%E6%A6%82%E5%BF%B5-toc" style="margin-left:0px;"><a href="#%E4%B8%80.%E5%BC%82%E5%B8%B8%E7%9A%84%E6%A6%82%E5%BF%B5" rel="nofollow">一.异常的概念</a></p> 
<p id="%E4%BA%8C.%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BD%93%E7%B3%BB%E7%BB%93%E6%9E%84-toc" style="margin-left:0px;"><a href="#%E4%BA%8C.%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BD%93%E7%B3%BB%E7%BB%93%E6%9E%84" rel="nofollow">二.异常的体系结构</a></p> 
<p id="%E4%B8%89.%E5%BC%82%E5%B8%B8%E7%9A%84%E5%A4%84%E7%90%86-toc" style="margin-left:0px;"><a href="#%E4%B8%89.%E5%BC%82%E5%B8%B8%E7%9A%84%E5%A4%84%E7%90%86" rel="nofollow">三.异常的处理</a></p> 
<p id="%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E6%80%9D%E8%B7%AF-toc" style="margin-left:40px;"><a href="#%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E6%80%9D%E8%B7%AF" rel="nofollow">异常处理思路</a></p> 
<p id="LBYL%EF%BC%9ALook%20Before%20You%20Leap-toc" style="margin-left:80px;"><a href="#LBYL%EF%BC%9ALook%20Before%20You%20Leap" rel="nofollow">LBYL：Look Before You Leap</a></p> 
<p id="EAFP%3A%20It's%20Easier%20to%20Ask%20Forgiveness%20than%20Permission-toc" style="margin-left:80px;"><a href="#EAFP%3A%20It'%20rel=">EAFP: It's Easier to Ask Forgiveness than Permission</a></p> 
<p id="%E5%BC%82%E5%B8%B8%E6%8A%9B%E5%87%BAthrow-toc" style="margin-left:40px;"><a href="#%E5%BC%82%E5%B8%B8%E6%8A%9B%E5%87%BAthrow" rel="nofollow">异常抛出throw</a></p> 
<p id="%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8D%95%E8%8E%B7-toc" style="margin-left:40px;"><a href="#%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8D%95%E8%8E%B7" rel="nofollow">异常的捕获</a></p> 
<p id="%E6%8F%90%E9%86%92%E5%A3%B0%E6%98%8Ethrows-toc" style="margin-left:80px;"><a href="#%E6%8F%90%E9%86%92%E5%A3%B0%E6%98%8Ethrows" rel="nofollow">提醒声明throws</a></p> 
<p id="%C2%A0try-catch%E6%8D%95%E8%8E%B7%E5%A4%84%E7%90%86-toc" style="margin-left:80px;"><a href="#%C2%A0try-catch%E6%8D%95%E8%8E%B7%E5%A4%84%E7%90%86" rel="nofollow"> try-catch捕获处理</a></p> 
<p id="finally%E7%9A%84%E4%BD%9C%E7%94%A8-toc" style="margin-left:80px;"><a href="#finally%E7%9A%84%E4%BD%9C%E7%94%A8" rel="nofollow">finally的作用</a></p> 
<p id="%E5%9B%9B.%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8%E7%B1%BB-toc" style="margin-left:0px;"><a href="#%E5%9B%9B.%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8%E7%B1%BB" rel="nofollow">四.自定义异常类</a></p> 
<hr id="hr-toc"> 
<p></p> 
<h2>一.异常的概念</h2> 
<p>有一句话说的很好 ”程序员不是在写BUG就是在改BUG” ，在日常开发中，程序员绞尽脑汁的去写出完美的代码，但是在程序运行过程中难免回遇见一些奇奇怪怪的问题。而这些问题与BUG总是很难去控制，用人类的思维去看明明是很完美的一个逻辑处理，但是交给编译器就产生的结果总会与我们的预期大相径庭，在Java中，我们将程序执行过程中发生的不正常的行为称为<span style="color:#be191c;"><strong><span style="background-color:#ffd7b9;">异常</span></strong></span>，比如什么<span style="color:#be191c;"><strong><span style="background-color:#ffd7b9;">算数异常</span></strong></span>啊，<span style="color:#be191c;"><strong><span style="background-color:#ffd7b9;">数组越界异常</span></strong></span>啊，<span style="color:#be191c;"><strong><span style="background-color:#ffd7b9;">空指针异常</span></strong></span>啊这都属于异常的范围，我们统称为异常</p> 
<pre><code class="language-java">        System.out.println(10 / 0);
        // 执行结果Exception in thread "main" java.lang.ArithmeticException
        
        int[] arr1 = {1, 2, 3};
        System.out.println(arr1[100]);
        // 执行结果Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException
        
        int[] arr2 = null;
        System.out.println(arr2.length);
        // 执行结果Exception in thread "main" java.lang.NullPointerException</code></pre> 
<p>并且我们可以看见<span style="color:#be191c;"><strong><span style="background-color:#ffd7b9;">在Java中对于不同的异常，都有对应的类来描述</span></strong></span></p> 
<hr> 
<h2 id="%E4%BA%8C.%E5%BC%82%E5%B8%B8%E7%9A%84%E4%BD%93%E7%B3%BB%E7%BB%93%E6%9E%84">二.异常的体系结构</h2> 
<p>实际上异常的种类是很多的，为了应对不同的异常或者错误，Java提供了一个非常庞大的异常体系机构供程序员来更好的维护代码的安全性，如下图所示</p> 
<p><img alt="" height="333" src="https://images2.imgbox.com/70/52/zcUQqI8u_o.png" width="664"></p> 
<p>异常可能发生在编译阶段，可能发生在运行阶段，因此我们可以按照异常发生的时间段将其进行分类：</p> 
<ul><li>编译时异常，也叫做受查异常</li><li>运行时异常，也叫做非受查异常 </li></ul> 
<p>但是诸如将单词拼写错误导致的问题我们程序出现问题的情况不属于异常</p> 
<hr> 
<h2 id="%E4%B8%89.%E5%BC%82%E5%B8%B8%E7%9A%84%E5%A4%84%E7%90%86">三.异常的处理</h2> 
<p>代码中存在异常并不是什么奇怪的事情，但是在出现异常后，我们需要及时通知程序员去修改，对于异常的处理，我们分为俩种思路</p> 
<h3 id="%E5%BC%82%E5%B8%B8%E5%A4%84%E7%90%86%E6%80%9D%E8%B7%AF">异常处理思路</h3> 
<h4 id="LBYL%EF%BC%9ALook%20Before%20You%20Leap">LBYL：Look Before You Leap</h4> 
<p>也就是说我们<span style="color:#be191c;"><strong><span style="background-color:#ffd7b9;">在操作之前就对异常做出充分的检查</span></strong></span>，也就是事先防御型，比如我们在设计一款游戏的时候，我们就需要对其中可能发生的每一个错误做出处理机制和避免机制</p> 
<pre><code class="language-java">        boolean ret = false;
        ret = loginGame();
        if (!ret) {
            //处理登陆游戏错误;
            return;
        }
        ret = startMatch();
        if (!ret) {
            //处理匹配错误;
            return;
        }
        ret = conGame();
        if (!ret) {
            //处理游戏确认错误;
            return;
        }
        ret = choiceChar();
        if (!ret) {
            //处理选择英雄错误;
            return;
        }
        ret = loading();
        if (!ret) {
            //处理载入游戏错误;
            return;
        }</code></pre> 
<p>但这样的处理会有一个<span style="color:#be191c;"><strong><span style="background-color:#ffd7b9;">缺陷：正常流程和错误处理流程代码混在一起, 代码整体显的比较混乱</span></strong></span></p> 
<h4 id="EAFP%3A%20It's%20Easier%20to%20Ask%20Forgiveness%20than%20Permission">EAFP: It's Easier to Ask Forgiveness than Permission</h4> 
<p>这样的思想主要解决的问题不是如何提前避免异常，而是在<span style="color:#be191c;"><strong><span style="background-color:#ffd7b9;">异常出现以后如何进行合理的应对</span></strong></span></p> 
<pre><code class="language-java">        try {
            loginGame();
            startMatch();
            conGame();
            choiceChar();
            loading();

        } catch (loginGame异常) {
            //处理登陆游戏错误;
        } catch (startMatch异常) {
            //处理匹配错误;
        } catch (conGame异常) {
            //处理游戏确认错误;
        } catch (choiceChar异常) {
            //处理选择英雄错误;
        } catch (loading异常) {
            //处理载入游戏错误;
        }</code></pre> 
<p>在Java中对于异常处理的核心机制就是EAFP，Java中<span style="color:#be191c;"><strong><span style="background-color:#ffd7b9;">常用的有5个异常处理的关键字</span></strong></span>：</p> 
<ul><li><span style="color:#f3f3f4;"><strong><span style="background-color:#0d0016;">throw</span></strong></span></li><li><span style="color:#f3f3f4;"><strong><span style="background-color:#0d0016;">try</span></strong></span></li><li><span style="color:#f3f3f4;"><strong><span style="background-color:#0d0016;">catch</span></strong></span></li><li><span style="color:#f3f3f4;"><strong><span style="background-color:#0d0016;">final</span></strong></span></li><li><span style="color:#f3f3f4;"><strong><span style="background-color:#0d0016;">throws</span></strong></span></li></ul> 
<h3 id="%E5%BC%82%E5%B8%B8%E6%8A%9B%E5%87%BAthrow">异常抛出throw</h3> 
<p>在Java中，可以借助<span style="color:#be191c;"><strong><span style="background-color:#ffd7b9;">throw关键字</span></strong></span>，抛出一个指定的异常对象，将错误信息告知给调用者。具体语法如下：</p> 
<blockquote> 
 <p><span style="color:#be191c;"><strong><span style="background-color:#ffd7b9;">throw</span></strong></span><strong> <span style="color:#ad720d;"><span style="background-color:#f9eda6;">new</span></span> </strong><strong><span style="color:#ad720d;"><span style="background-color:#f9eda6;">XXXException</span></span> </strong><strong>("异常产生的原因")</strong>;</p> 
</blockquote> 
<p><strong>示例： </strong></p> 
<pre><code class="language-java">    public static int getElement(int[] array, int index){
        if(null == array){
            throw new NullPointerException("传递的数组为null");
        }
        if(index &lt; 0 || index &gt;= array.length){
            throw new ArrayIndexOutOfBoundsException("传递的数组下标越界");
        }
        return array[index];
    }
    public static void main(String[] args) {
        int[] array = {1, 2, 3};
        getElement(array, 3);
    }</code></pre> 
<p><strong> 注意：</strong></p> 
<ol><li><strong>throw </strong>必须写在方法体内部</li><li>抛出的对象必须是<strong>Exception </strong>或者 <strong>Exception </strong>的子类对象</li><li>如果抛出的是 <strong>RunTimeException </strong>或者 <strong>RunTimeException </strong>的子类，则可以不用处理，直接交给<strong>JVM</strong>来处理</li><li>如果抛出的是编译时异常，用户必须处理，否则无法通过编译</li><li>异常一旦抛出，其后的代码就不会执行</li></ol> 
<h3 id="%E5%BC%82%E5%B8%B8%E7%9A%84%E6%8D%95%E8%8E%B7">异常的捕获</h3> 
<p>异常的捕获就是指我们对异常的处理，通常我们有俩种方式去处理：</p> 
<ul><li>异常声明throws</li><li>try-catch捕获处理</li></ul> 
<h4 id="%E6%8F%90%E9%86%92%E5%A3%B0%E6%98%8Ethrows">提醒声明throws</h4> 
<p>处在方法声明时参数列表之后，当方法中抛出编译时异常，用户不想处理该异常，此时就可以借助<strong>throws</strong>将异常抛给方法的调用者来处理。也就是说<span style="color:#be191c;"><strong><span style="background-color:#ffd7b9;">当前方法不处理异常</span></strong><span style="background-color:#ffd7b9;">，</span><strong><span style="background-color:#ffd7b9;">提醒方法的调用者处理异常</span></strong></span>。</p> 
<blockquote> 
 <p><strong>语法格式： </strong></p> 
 <p><strong>修饰符 </strong><strong>返回值类型</strong> <strong>方法名</strong> <strong>(参数列表</strong><strong>)</strong> <strong><span style="color:#be191c;"><span style="background-color:#ffd7b9;">throws</span></span> </strong><span style="color:#ad720d;"><strong><span style="background-color:#f9eda6;">异常类型1，异常类型2...</span></strong></span>{<!-- --></p> 
 <p>}</p> 
</blockquote> 
<pre><code class="language-java">public class Config {
    File file;
    /*
    FileNotFoundException : 编译时异常，表明文件不存在
    此处不处理，也没有能力处理，应该将错误信息报告给调用者，让调用者检查文件名字是否给错误了
    */
    public void OpenConfig(String filename) throws FileNotFoundException {
        if (filename.equals("config.ini")) {
            throw new FileNotFoundException("配置文件名字不对");
        }
        // 打开文件
    }
}</code></pre> 
<p><strong>注意事项：</strong></p> 
<ul><li><strong>throws </strong>必须跟在方法参数列表之后</li><li>抛出的问题必须是<strong>Exception </strong>或者 <strong>Exception </strong>的子类对象</li><li>方法内部如果抛出了多个异常，<strong>throws </strong>之后必须跟多个异常类型，之间用逗号隔开，如果抛出多个异常类型具有父子关系，直接声明父类即可</li><li>调用声明抛出的异常方法时，调用者必须对异常做出处理，或者继续使用<strong>throws </strong>抛出</li></ul> 
<p><strong>示例： </strong></p> 
<pre><code class="language-java">class Config {
    File file;
    // FileNotFoundException 继承自 IOException
    public void OpenConfig(String filename) throws IOException {
        if(filename.endsWith(".ini")){
            throw new IOException("文件不是.ini文件");
        }
        if(filename.equals("config.ini")){
            throw new FileNotFoundException("配置文件名字不对");
        }
        // 打开文件
    }
    public void readConfig(){
    }
    public void openConfig(String s) {
    }
    public static void main(String[] args) throws IOException {
        Config config = new Config();
        config.openConfig("config.ini");
    }
}
</code></pre> 
<h4 id="%C2%A0try-catch%E6%8D%95%E8%8E%B7%E5%A4%84%E7%90%86"> try-catch捕获处理</h4> 
<p>刚才我们提到的<span style="color:#be191c;"><strong><span style="background-color:#ffd7b9;">throws </span></strong></span>并没有对异常做出处理，他只是将异常报给调用者，让调用者去处理，而如果要对异常真正的处理就需要使用<span style="color:#be191c;"><strong><span style="background-color:#ffd7b9;">try-catch</span></strong></span>。</p> 
<p><span style="color:#be191c;"><strong><span style="background-color:#ffd7b9;">try-catch</span></strong></span>的一般使用语法如下，其中<span style="color:#be191c;"><strong><span style="background-color:#ffd7b9;">catch</span></strong></span>：可以有一个也可以有多个，根据具体需求分配，<span style="color:#be191c;"><strong><span style="background-color:#ffd7b9;">finally</span></strong></span>可以有也可以没有，但是如果有的话<span style="color:#be191c;"><strong><span style="background-color:#ffd7b9;">finally</span></strong></span>中的代码就一定会执行，并且<span style="color:#be191c;"><strong><span style="background-color:#ffd7b9;">try</span></strong></span>中的代码也可以不出现异常：</p> 
<pre><code class="language-java">try{
    // 将可能出现异常的代码放在这里
    }catch(要捕获的异常类型 e){
        // 如果try中的代码抛出异常了，此处catch捕获时异常类型与try中抛出的异常类型一致时
        //或者是try中抛出异常的基类时，就会被捕获到
        //对异常就可以正常处理，处理完成后，跳出try-catch结构，继续执行后序代码
    }catch(异常类型 e){
        // 对异常进行处理
    }finally{
        // 此处代码一定会被执行到
    }
}</code></pre> 
<p><strong>示例：</strong></p> 
<pre><code class="language-java">class Config {
    File file;
    public void openConfig(String filename) throws FileNotFoundException{
        if(!filename.equals("config.ini")){
            throw new FileNotFoundException("配置文件名字不对");
        }
        // 打开文件
    }
    public void readConfig(){
    }
    public static void main(String[] args) {
        Config config = new Config();
        try {
            config.openConfig("config.txt");
            System.out.println("文件打开成功");
        } catch (IOException e) {
        // 异常的处理方式
        //System.out.println(e.getMessage()); // 只打印异常信息
        //System.out.println(e); // 打印异常类型：异常信息
            e.printStackTrace(); // 打印信息最全面
        }
        // 一旦异常被捕获处理了，此处的代码会执行
        System.out.println("异常如果被处理了，这里的代码也可以执行");
    }
}</code></pre> 
<p><strong>注意：</strong></p> 
<ul><li> <strong>try </strong>块内抛出异常位置之后的代码将不会被执行</li><li> 如果抛出异常类型与<strong>catch</strong>时异常类型不匹配，即异常不会被成功捕获，也就不会被处理，继续往外抛，直到JVM收到后中断程序----异常是按照类型来捕获的</li><li> <strong>try </strong>中可能会抛出多个不同的异常对象，则必须用多个<strong>catch</strong>来捕获----即多种异常，多次捕获</li><li>如果异常之间具有父子关系，一定是子类异常在前<strong>catch</strong>，父类异常在后<strong>catch</strong>，否则语法错误</li></ul> 
<h4 id="finally%E7%9A%84%E4%BD%9C%E7%94%A8">finally的作用</h4> 
<p>在写程序时，有些特定的代码，不论程序是否发生异常，都需要执行，比如程序中打开的资源：网络连接、数据库连接、IO流等，在程序正常或者异常退出时，必须要对资源进进行回收。另外，因为异常会引发程序的跳转，可能导致有些语句执行不到，<span style="color:#be191c;"><strong><span style="background-color:#ffd7b9;">finally</span></strong></span>就是用来解决这个问题的。</p> 
<blockquote> 
 <p>关于异常的处理方式，异常的种类有很多，我们要根据不同的业务场景来决定</p> 
 <ul><li>对于比较严重的问题(例如和算钱相关的场景), 应该让程序直接崩溃, 防止造成更严重的后果</li><li>对于不太严重的问题(大多数场景), 可以记录错误日志, 并通过监控报警程序及时通知程序猿</li><li>对于可能会恢复的问题(和网络相关的场景), 可以尝试进行重试</li><li>在我们当前的代码中采取的是经过简化的第二种方式. 我们记录的错误日志是出现异常的方法调用信息, 能很快速的让我们找到出现异常的位置. 以后在实际工作中我们会采取更完备的方式来记录异常信息</li></ul> 
</blockquote> 
<h2 id="%E5%9B%9B.%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8%E7%B1%BB">四.自定义异常类</h2> 
<p>Java中虽然已经内置了丰富的异常类, 但是并不能完全表示实际开发中所遇到的一些异常，此时就需要维护符合我们实际情况的异常结构，自定义异常通常会继承自 <strong><span style="color:#be191c;"><span style="background-color:#ffd7b9;">Exception</span></span></strong>或<strong><span style="color:#be191c;"><span style="background-color:#ffd7b9;">RunTimeException</span></span></strong></p> 
<ul><li>继承自 <strong>Exception</strong> 的异常默认是受查异常</li><li>继承自 <strong>RunTimeException</strong> 的异常默认是非受查异常</li></ul> 
<blockquote> 
 <p>具体方式：</p> 
 <ol><li>自定义异常类，然后继承自<strong><span style="background-color:#ff9900;">Exception</span></strong><span style="background-color:#ff9900;"> </span>或者 <strong><span style="background-color:#ff9900;">RunTimeException</span></strong><span style="background-color:#ff9900;"> </span></li><li>实现一个带有<strong>String</strong>类型参数的构造方法，参数含义：出现异常的原因</li></ol> 
</blockquote> 
<p>例如我们实现一个用户登陆功能： </p> 
<pre><code class="language-java">class UserNameException extends Exception {
    public UserNameException(String message) {
        super(message);
    }
}
class PasswordException extends Exception {
    public PasswordException(String message) {
        super(message);
    }
}</code></pre> 
<pre><code class="language-java">class LogIn {
    private String userName = "admin";
    private String password = "123456";
    public static void loginInfo(String userName, String password)
            throws UserNameException,PasswordException{
        if (!userName.equals(userName)) {
            throw new UserNameException("用户名错误！");
        }
        if (!password.equals(password)) {
            throw new PasswordException("用户名错误！");
        }
        System.out.println("登陆成功");
    }
    public static void main(String[] args) {
        try {
            loginInfo("admin", "123456");
        } catch (UserNameException e) {
            e.printStackTrace();
        } catch (PasswordException e) {
            e.printStackTrace();
        }
    }
}</code></pre> 
<hr> 
<hr> 
<hr> 
<p><img alt="" height="23" src="https://images2.imgbox.com/8f/21/0jSp1rWD_o.png" width="23"><strong> 本次的分享就到此为止了，希望我的分享能给您带来帮助，也欢迎大家三连支持，你们的点赞就是博主更新最大的动力！</strong><img alt="" height="23" src="https://images2.imgbox.com/73/db/EIzha9CR_o.png" width="23"><strong>如有不同意见，欢迎评论区积极讨论交流，让我们一起学习进步！</strong><img alt="" height="23" src="https://images2.imgbox.com/5f/21/TaoWdPke_o.png" width="23"><strong>有相关问题也可以私信博主，评论区和私信都会认真查看的，我们下次再见</strong><img alt="" height="23" src="https://images2.imgbox.com/a2/fc/72G0lcal_o.png" width="23"></p>
                </div>
		</div>
		<div id="gabottom"></div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/d765cf764e075e7995eb88761a28803d/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">操作系统实验：首次适应算法、最佳适应算法、最坏适应算法</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/f06dfbcf9dd3801be7c5128db0f44bdf/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">uniapp-安卓调试打包发布超详细！！流程</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 编程学习者.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<div id="gafoot"></div>
<script src="https://www.w3counter.com/tracker.js?id=151347"></script>
<script src="https://101121.xyz/ga/app.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>